# Generated by Django 3.2 on 2025-12-08 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercise_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='reps',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='sets',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='workout',
            name='user_id',
            field=models.CharField(db_index=True, default='public-user', max_length=255),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['created_at'], name='workouts_created_932877_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['exercise_name'], name='workouts_exercis_eb52c1_idx'),
        ),
        migrations.AddIndex(
            model_name='workout',
            index=models.Index(fields=['user_id', 'created_at'], name='workouts_user_id_7c8885_idx'),
        ),
    ]
